version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-deadline
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  sut:
    image: openjdk:17
    container_name: sut-deadline
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./app-deadline.jar:/app/app-deadline.jar
    command: >
      java -jar app-deadline.jar
      -P:jdbc.url=jdbc:mysql://mysql-deadline:3306/app
      -P:jdbc.user=app
      -P:jdbc.password=pass
    ports:
      - "9999:9999"
